[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.128.0",
    "paramiko>=4.0.0",
]


[tool.pyright]
venvPath = ".devenv/state"
venv = "venv"
include = ["**/*.py"]
exclude = ["**/node_modules", "**/__pycache__"]
pythonVersion = "3.13"

[dependency-groups]
dev = [
    "pytest>=9.0.2",
]
